// src/components/chat/MessageInput.tsx

import React, { useRef, useState, useEffect } from "react";
import {
  Send,
  Paperclip,
  Smile,
  X,
  FileText,
  Image as ImageIcon,
} from "lucide-react";
import ReplyPreview from "./ReplyPreview";

export interface ReplyTarget {
  id: string;
  senderName: string;
  content: string;
}

export interface AttachmentFile {
  file: File;
  previewUrl: string | null;
  type: "image" | "video" | "audio" | "pdf" | "document";
}

// ── Full emoji categories (all provided emojis + original set) ────────────────

const EMOJI_CATEGORIES: { label: string; icon: string; emojis: string[] }[] = [
  {
    label: "Smileys",
    icon: "😀",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "🥹",
      "😅",
      "😂",
      "🤣",
      "🥲",
      "☺️",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😌",
      "😍",
      "🥰",
      "😘",
      "😗",
      "😙",
      "😚",
      "😋",
      "😛",
      "😝",
      "😜",
      "🤪",
      "🤓",
      "😎",
      "🥸",
      "🤩",
      "🥳",
      "😏",
      "😒",
      "😞",
      "😔",
      "😟",
      "😕",
      "🙁",
      "☹️",
      "😣",
      "😖",
      "😫",
      "😩",
      "🥺",
      "😢",
      "😭",
      "😤",
      "😠",
      "😡",
      "🤬",
      "🤯",
      "😳",
      "🥵",
      "🥶",
      "😱",
      "😨",
      "😰",
      "😥",
      "😓",
      "🤗",
      "🤔",
      "🫣",
      "🤭",
      "🤫",
      "🫡",
      "🤥",
      "😶",
      "🫥",
      "😐",
      "🫤",
      "😑",
      "🫨",
      "😬",
      "🙄",
      "😯",
      "😦",
      "😧",
      "😮",
      "😲",
      "🥴",
      "😴",
      "🤤",
      "😪",
      "🥱",
      "🤢",
      "🤮",
      "🤧",
      "😷",
      "🤒",
      "🤕",
      "🤑",
      "🤠",
      "😈",
      "👿",
      "👹",
      "👺",
      "☠️",
      "💀",
      "👻",
      "👽",
      "👾",
      "🤡",
      "💩",
      "😸",
      "😺",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
      "🎃",
    ],
  },
  {
    label: "Gestures",
    icon: "👍",
    emojis: [
      "👋",
      "🤚",
      "✋",
      "🖐️",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "🫶",
      "🤲",
      "👐",
      "🙏",
      "🫱",
      "🫲",
      "🫳",
      "🫴",
      "🫵",
      "💪",
      "🦾",
      "🖕",
      "✍️",
      "🤳",
      "💅",
      "🦿",
      "🦵",
      "🦶",
      "👂",
      "🦻",
      "👃",
      "👣",
      "👁️",
      "👀",
      "🫀",
      "🫁",
      "🧠",
      "🗣️",
      "👤",
      "👥",
      "🫂",
    ],
  },
  {
    label: "People",
    icon: "👶",
    emojis: [
      "👶",
      "🧒",
      "👦",
      "👧",
      "🧑",
      "👱",
      "👨",
      "🧔",
      "👩",
      "🧓",
      "👴",
      "👵",
      "🧕",
      "👮",
      "💂",
      "🕵️",
      "👷",
      "🫅",
      "🤴",
      "👸",
      "🧙",
      "🧝",
      "🧛",
      "🧟",
      "🧞",
      "🧜",
      "🧚",
      "👼",
      "🤰",
      "🫄",
      "🫃",
      "🤱",
      "🙇",
      "🙋",
      "🙆",
      "🙅",
      "💁",
      "🤦",
      "🤷",
      "🙎",
      "🙍",
      "🧖",
      "💆",
      "💇",
      "💃",
      "🕺",
      "🧍",
      "🚶",
      "🏃",
      "🧎",
      "👩‍🦼",
      "🧑‍🦼",
      "👨‍🦼",
      "👩‍🦽",
      "🧑‍🦽",
      "👨‍🦽",
      "👩‍🦯",
      "🧑‍🦯",
      "👨‍🦯",
      "💑",
      "👬",
      "👭",
      "👫",
      "👨‍❤️‍👨",
      "👩‍❤️‍👩",
      "👩‍❤️‍👨",
      "💏",
      "👩‍❤️‍💋‍👨",
      "👩‍❤️‍💋‍👩",
      "👨‍❤️‍💋‍👨",
      "🧑‍🧒",
      "🧑‍🧒‍🧒",
      "🧑‍🧑‍🧒",
      "🧑‍🧑‍🧒‍🧒",
    ],
  },
  {
    label: "Clothing",
    icon: "👗",
    emojis: [
      "🧥",
      "🥼",
      "🦺",
      "👔",
      "👕",
      "👖",
      "👗",
      "👘",
      "🥻",
      "🩱",
      "👙",
      "🩲",
      "🩳",
      "🧦",
      "🧤",
      "🧣",
      "🎩",
      "🧢",
      "👒",
      "🎓",
      "⛑️",
      "🪖",
      "👓",
      "🕶️",
      "🥽",
      "🌂",
      "☂️",
      "🧳",
      "🎒",
      "💼",
      "👜",
      "👛",
      "👝",
      "💍",
      "👑",
      "🥿",
      "👠",
      "👡",
      "👢",
      "👞",
      "👟",
      "🥾",
      "🩴",
      "🪢",
      "🧵",
      "🪡",
      "🧶",
    ],
  },
  {
    label: "Animals",
    icon: "🐶",
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐻‍❄️",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐽",
      "🐸",
      "🐵",
      "🙈",
      "🙉",
      "🙊",
      "🐒",
      "🐔",
      "🐧",
      "🐦",
      "🦆",
      "🪿",
      "🦅",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🫎",
      "🐝",
      "🪱",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🦟",
      "🦗",
      "🕷️",
      "🕸️",
      "🦂",
      "🐢",
      "🐍",
      "🦎",
      "🦖",
      "🦕",
      "🐙",
      "🦑",
      "🦭",
      "🦈",
      "🐋",
      "🐳",
      "🐬",
      "🐟",
      "🐠",
      "🐡",
      "🦀",
      "🦞",
      "🦐",
      "🪼",
      "🐊",
      "🐅",
      "🐆",
      "🦓",
      "🦍",
      "🦧",
      "🦣",
      "🐘",
      "🦛",
      "🦏",
      "🐪",
      "🐫",
      "🦙",
      "🐑",
      "🐏",
      "🐖",
      "🐎",
      "🫏",
      "🐄",
      "🐂",
      "🐃",
      "🦬",
      "🦘",
      "🦒",
      "🐐",
      "🦌",
      "🐕",
      "🐩",
      "🦮",
      "🐕‍🦺",
      "🐈",
      "🐈‍⬛",
      "🪶",
      "🪽",
      "🐓",
      "🦃",
      "🦦",
      "🦫",
      "🦡",
      "🦨",
      "🦝",
      "🐇",
      "🕊️",
      "🦩",
      "🦢",
      "🦜",
      "🦚",
      "🦤",
      "🦥",
      "🐁",
      "🐀",
      "🐿️",
      "🦔",
      "🐾",
      "🐉",
      "🐲",
      "🐦‍🔥",
      "🐦‍⬛",
      "🪳",
      "🪲",
      "🪰",
    ],
  },
  {
    label: "Nature",
    icon: "🌿",
    emojis: [
      "🌵",
      "🎄",
      "🌲",
      "🌳",
      "🌴",
      "🌱",
      "🌿",
      "☘️",
      "🍀",
      "🎋",
      "🪴",
      "🎍",
      "🍃",
      "🍂",
      "🍁",
      "🪺",
      "🪹",
      "🍄",
      "🍄‍🟫",
      "🐚",
      "🪸",
      "🪨",
      "🌾",
      "💐",
      "🌷",
      "🌹",
      "🥀",
      "🪷",
      "🪻",
      "🌸",
      "🌺",
      "🌻",
      "🌼",
      "🌝",
      "🌜",
      "🌛",
      "🌚",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌑",
      "🌒",
      "🌓",
      "🌔",
      "🌙",
      "🌎",
      "🌍",
      "🌏",
      "🪐",
      "☀️",
      "🌈",
      "🌪️",
      "🔥",
      "💥",
      "☄️",
      "⚡",
      "✨",
      "🌟",
      "⭐",
      "💫",
      "🌤️",
      "⛅",
      "🌥️",
      "☁️",
      "🌦️",
      "🌧️",
      "⛈️",
      "🌩️",
      "🌨️",
      "❄️",
      "☃️",
      "⛄",
      "🌫️",
      "🌊",
      "☂️",
      "☔",
      "🫧",
      "💦",
      "💧",
      "💨",
      "🌬️",
    ],
  },
  {
    label: "Food",
    icon: "🍕",
    emojis: [
      "🍏",
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍋‍🟩",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🥬",
      "🥦",
      "🫛",
      "🥑",
      "🍆",
      "🍅",
      "🥝",
      "🥥",
      "🍍",
      "🥭",
      "🍑",
      "🍒",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🫒",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🫚",
      "🥐",
      "🥩",
      "🥓",
      "🧇",
      "🥞",
      "🧈",
      "🍳",
      "🥚",
      "🧀",
      "🥨",
      "🥖",
      "🍞",
      "🥯",
      "🍗",
      "🍖",
      "🦴",
      "🌭",
      "🍔",
      "🍟",
      "🍕",
      "🫓",
      "🥪",
      "🥙",
      "🧆",
      "🌮",
      "🌯",
      "🫔",
      "🍱",
      "🥟",
      "🦪",
      "🍤",
      "🍙",
      "🍚",
      "🍘",
      "🍥",
      "🥠",
      "🥮",
      "🍢",
      "🍡",
      "🍣",
      "🍛",
      "🍲",
      "🍜",
      "🍝",
      "🫙",
      "🥫",
      "🫕",
      "🥘",
      "🥗",
      "🍿",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🎂",
      "🍰",
      "🧁",
      "🥧",
      "🍦",
      "🍨",
      "🍧",
      "🍪",
      "🍩",
      "🌰",
      "🥜",
      "🫘",
      "🍯",
      "🥛",
      "🫗",
      "🍼",
      "🫖",
      "☕",
      "🍵",
      "🧉",
      "🍹",
      "🍸",
      "🥃",
      "🍷",
      "🥂",
      "🍻",
      "🍺",
      "🍶",
      "🧋",
      "🥤",
      "🧃",
      "🍾",
      "🧊",
      "🥄",
      "🍴",
      "🍽️",
      "🥣",
      "🥡",
      "🥢",
      "🧂",
    ],
  },
  {
    label: "Activities",
    icon: "⚽",
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🪀",
      "🏓",
      "🏸",
      "🥊",
      "🥋",
      "🎽",
      "🛹",
      "🛼",
      "🛷",
      "⛸️",
      "🥌",
      "🎿",
      "⛷️",
      "🏂",
      "🪂",
      "🏋️",
      "🤸",
      "🤼",
      "🤺",
      "🤾",
      "🏌️",
      "🏇",
      "🧘",
      "🚣",
      "🤽",
      "🏊",
      "🏄",
      "🧗",
      "🚵",
      "🚴",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🏅",
      "🎖️",
      "🏵️",
      "🎗️",
      "🎫",
      "🎟️",
      "🎪",
      "🤹",
      "🎭",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎹",
      "🪇",
      "🥁",
      "🪘",
      "🎷",
      "🎺",
      "🎻",
      "🪕",
      "🎸",
      "🪗",
      "🎲",
      "🧩",
      "🎰",
      "🎮",
      "🕹️",
      "🎯",
      "🎣",
      "🤿",
      "🏹",
      "⛳",
      "🥅",
      "🪁",
      "🏏",
      "🥍",
      "🏑",
      "🏒",
      "🛝",
      "🩰",
      "♟️",
      "🪈",
    ],
  },
  {
    label: "Travel",
    icon: "✈️",
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🏍️",
      "🛵",
      "🚲",
      "🛴",
      "🛞",
      "🛺",
      "🩼",
      "🦼",
      "🦽",
      "🦯",
      "🚨",
      "🚔",
      "🚍",
      "🚘",
      "🚖",
      "🚡",
      "🚠",
      "🚟",
      "🚃",
      "🚋",
      "🚞",
      "🚝",
      "🚄",
      "🚅",
      "🚆",
      "🚂",
      "🚈",
      "🚇",
      "🚊",
      "🚉",
      "✈️",
      "🛩️",
      "🛫",
      "🛬",
      "🪂",
      "💺",
      "🚀",
      "🛸",
      "🚁",
      "🛶",
      "⛵",
      "🚤",
      "🛥️",
      "🛳️",
      "⛴️",
      "🚢",
      "🗺️",
      "🗼",
      "🗽",
      "🗿",
      "🏰",
      "🏯",
      "🏟️",
      "🎡",
      "🎢",
      "🎠",
      "⛲",
      "⛱️",
      "🏖️",
      "🏝️",
      "🏜️",
      "🌋",
      "🏭",
      "🏗️",
      "🏚️",
      "🏘️",
      "🏡",
      "🏠",
      "🛖",
      "⛺",
      "🏕️",
      "🗻",
      "🏔️",
      "⛰️",
      "🏢",
      "🏬",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏪",
      "🏫",
      "🏩",
      "💒",
      "🏛️",
      "⛩️",
      "🕋",
      "🛕",
      "🕍",
      "🕌",
      "⛪",
      "🚏",
      "🚥",
      "🚦",
      "🚧",
      "⛽",
      "🪝",
      "⚓",
      "🛟",
      "🌅",
      "🏞️",
      "🎑",
      "🗾",
      "🛣️",
      "🛤️",
      "🌄",
      "🌠",
      "🎇",
      "🎆",
      "🌇",
      "🌆",
      "🏙️",
      "🌃",
      "🌌",
      "🌉",
      "🌁",
    ],
  },
  {
    label: "Objects",
    icon: "💡",
    emojis: [
      "💽",
      "🗜️",
      "🕹️",
      "🖲️",
      "🖱️",
      "🖨️",
      "🖥️",
      "⌨️",
      "💻",
      "📲",
      "📱",
      "⌚",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "🕰️",
      "⏰",
      "⏲️",
      "⏱️",
      "🧭",
      "🎛️",
      "🎚️",
      "🎙️",
      "📻",
      "📺",
      "📠",
      "📟",
      "⌛",
      "⏳",
      "📡",
      "🔋",
      "🪫",
      "🔌",
      "💡",
      "🔦",
      "🕯️",
      "🪔",
      "🧯",
      "🛢️",
      "🪜",
      "⚖️",
      "💎",
      "🪪",
      "💳",
      "💰",
      "🪙",
      "💷",
      "💶",
      "💴",
      "💵",
      "💸",
      "🧰",
      "🪛",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🪚",
      "🔩",
      "⚙️",
      "🪤",
      "🧱",
      "🚬",
      "🛡️",
      "⚔️",
      "🗡️",
      "🔪",
      "🪓",
      "🧨",
      "💣",
      "🔫",
      "🧲",
      "⛓️",
      "⚰️",
      "🪦",
      "⚱️",
      "🏺",
      "🔮",
      "📿",
      "🧿",
      "🪬",
      "💈",
      "⚗️",
      "🔭",
      "🔬",
      "🌡️",
      "🧪",
      "🧫",
      "🦠",
      "🧬",
      "🩸",
      "💉",
      "💊",
      "🩺",
      "🩹",
      "🩻",
      "🕳️",
      "🧹",
      "🪠",
      "🧺",
      "🧻",
      "🚽",
      "🚰",
      "🚿",
      "🛁",
      "🛀",
      "🧼",
      "🪥",
      "🪒",
      "🛌",
      "🛏️",
      "🛋️",
      "🪑",
      "🚪",
      "🗝️",
      "🔑",
      "🛎️",
      "🧴",
      "🪣",
      "🧽",
      "🪮",
      "🧸",
      "🪆",
      "🖼️",
      "🪞",
      "🪟",
      "🛍️",
      "🛒",
      "🎁",
      "🎈",
      "🎏",
      "🎀",
      "🪄",
      "🪩",
      "🎐",
      "🏮",
      "🪭",
      "🎎",
      "🧧",
    ],
  },
  {
    label: "Symbols",
    icon: "❤️",
    emojis: [
      "🩷",
      "❤️",
      "🧡",
      "💛",
      "💚",
      "🩵",
      "💙",
      "💜",
      "🖤",
      "🩶",
      "🤍",
      "🤎",
      "💟",
      "💝",
      "💘",
      "💖",
      "💗",
      "💓",
      "💞",
      "💕",
      "❣️",
      "❤️‍🩹",
      "❤️‍🔥",
      "💔",
      "☮️",
      "✝️",
      "☪️",
      "🕉️",
      "☸️",
      "🪯",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "♒",
      "♑",
      "♐",
      "♏",
      "♎",
      "♍",
      "♌",
      "♋",
      "♊",
      "♉",
      "♈",
      "⛎",
      "♓",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🅰️",
      "🈲",
      "🅱️",
      "🆎",
      "🆑",
      "🅾️",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "❗",
      "❕",
      "❓",
      "❔",
      "‼️",
      "⁉️",
      "🔅",
      "🔆",
      "〽️",
      "⚠️",
      "🚸",
      "🔱",
      "⚜️",
      "🔰",
      "♻️",
      "✅",
      "🈯",
      "💹",
      "❎",
      "✳️",
      "❇️",
      "🆚",
      "🈷️",
      "🈹",
      "🈵",
      "🈴",
      "㊗️",
      "㊙️",
      "🉐",
      "💮",
      "✴️",
      "🅿️",
      "🛗",
      "🈳",
      "🈂️",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "🛜",
      "🚹",
      "🚺",
      "🚼",
      "🚻",
      "⚧️",
      "🔣",
      "ℹ️",
      "🔤",
      "🔡",
      "🔠",
      "🆖",
      "🆗",
      "🆙",
      "🆒",
      "🆕",
      "🆓",
      "🔢",
      "🔟",
      "🔊",
      "🔉",
      "🔇",
      "🔈",
      "🔔",
      "🔕",
      "📣",
      "📢",
      "💬",
      "💭",
      "🗯️",
      "♠️",
      "♣️",
      "♥️",
      "♦️",
      "🃏",
      "🀄",
      "🎴",
      "🏧",
      "💤",
      "🌀",
      "Ⓜ️",
      "💠",
      "🌐",
      "🔗",
      "🧷",
      "🔖",
      "📌",
      "📍",
      "✂️",
      "✏️",
      "📝",
      "🖍️",
      "🖊️",
      "🖋️",
      "✒️",
      "🖌️",
      "🔓",
      "🔒",
      "🔐",
      "🔏",
      "🔎",
      "🔍",
      "♾️",
      "🟰",
      "✖️",
      "➗",
      "➖",
      "➕",
      "🎵",
      "🎶",
      "®️",
      "©️",
      "™️",
      "💱",
      "💲",
      "🔚",
      "🔙",
      "🔛",
      "🔝",
      "🔜",
      "〰️",
      "➰",
      "➿",
      "✔️",
      "☑️",
      "🔘",
      "🔸",
      "🔻",
      "🔺",
      "🟤",
      "⚪",
      "⚫",
      "🟣",
      "🔵",
      "🟢",
      "🟡",
      "🟠",
      "🔴",
      "🔹",
      "🔶",
      "🔷",
      "🔳",
      "🔲",
      "▪️",
      "▫️",
      "◾",
      "◽",
      "◼️",
      "◻️",
      "🟥",
      "🟫",
      "⬜",
      "⬛",
      "🟪",
      "🟦",
      "🟩",
      "🟨",
      "🟧",
      "🕙",
      "🕘",
      "🕗",
      "🕖",
      "🕕",
      "🕔",
      "🕓",
      "🕒",
      "🕑",
      "🕐",
      "🕚",
      "🕛",
      "🕜",
      "🕝",
      "🕞",
      "🕟",
      "🕠",
      "🕡",
      "🕢",
      "🕣",
      "🕤",
      "🕥",
      "🕦",
      "🕧",
    ],
  },
  {
    label: "Flags",
    icon: "🏳️",
    emojis: [
      "🏳️",
      "🏴",
      "🏴‍☠️",
      "🏁",
      "🚩",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🇺🇳",
      "🇦🇫",
      "🇦🇱",
      "🇩🇿",
      "🇦🇩",
      "🇦🇴",
      "🇦🇮",
      "🇦🇶",
      "🇦🇬",
      "🇦🇷",
      "🇦🇲",
      "🇦🇼",
      "🇦🇺",
      "🇦🇹",
      "🇦🇿",
      "🇧🇸",
      "🇧🇭",
      "🇧🇩",
      "🇧🇧",
      "🇧🇾",
      "🇧🇪",
      "🇧🇿",
      "🇧🇯",
      "🇧🇲",
      "🇧🇹",
      "🇧🇴",
      "🇧🇦",
      "🇧🇼",
      "🇧🇷",
      "🇧🇳",
      "🇧🇬",
      "🇧🇫",
      "🇧🇮",
      "🇨🇻",
      "🇰🇭",
      "🇨🇲",
      "🇨🇦",
      "🇰🇾",
      "🇨🇫",
      "🇹🇩",
      "🇨🇱",
      "🇨🇳",
      "🇨🇴",
      "🇰🇲",
      "🇨🇩",
      "🇨🇬",
      "🇨🇰",
      "🇨🇷",
      "🇨🇮",
      "🇭🇷",
      "🇨🇺",
      "🇨🇼",
      "🇨🇾",
      "🇨🇿",
      "🇩🇰",
      "🇩🇯",
      "🇩🇲",
      "🇩🇴",
      "🇪🇨",
      "🇪🇬",
      "🇸🇻",
      "🇬🇶",
      "🇪🇷",
      "🇪🇪",
      "🇸🇿",
      "🇪🇹",
      "🇪🇺",
      "🇫🇰",
      "🇫🇯",
      "🇫🇮",
      "🇫🇷",
      "🇬🇫",
      "🇵🇫",
      "🇹🇫",
      "🇬🇦",
      "🇬🇲",
      "🇬🇪",
      "🇩🇪",
      "🇬🇭",
      "🇬🇮",
      "🇬🇷",
      "🇬🇱",
      "🇬🇩",
      "🇬🇵",
      "🇬🇺",
      "🇬🇹",
      "🇬🇬",
      "🇬🇳",
      "🇬🇼",
      "🇬🇾",
      "🇭🇹",
      "🇭🇳",
      "🇭🇰",
      "🇭🇺",
      "🇮🇸",
      "🇮🇳",
      "🇮🇩",
      "🇮🇷",
      "🇮🇶",
      "🇮🇪",
      "🇮🇲",
      "🇮🇱",
      "🇮🇹",
      "🇯🇲",
      "🇯🇵",
      "🎌",
      "🇯🇪",
      "🇯🇴",
      "🇰🇿",
      "🇰🇪",
      "🇰🇮",
      "🇽🇰",
      "🇰🇼",
      "🇰🇬",
      "🇱🇦",
      "🇱🇻",
      "🇱🇧",
      "🇱🇸",
      "🇱🇷",
      "🇱🇾",
      "🇱🇮",
      "🇱🇹",
      "🇱🇺",
      "🇲🇴",
      "🇲🇬",
      "🇲🇼",
      "🇲🇾",
      "🇲🇻",
      "🇲🇱",
      "🇲🇹",
      "🇲🇭",
      "🇲🇶",
      "🇲🇷",
      "🇲🇺",
      "🇾🇹",
      "🇲🇽",
      "🇫🇲",
      "🇲🇩",
      "🇲🇨",
      "🇲🇳",
      "🇲🇪",
      "🇲🇸",
      "🇲🇦",
      "🇲🇿",
      "🇲🇲",
      "🇳🇦",
      "🇳🇷",
      "🇳🇵",
      "🇳🇱",
      "🇳🇨",
      "🇳🇿",
      "🇳🇮",
      "🇳🇪",
      "🇳🇬",
      "🇳🇺",
      "🇳🇫",
      "🇰🇵",
      "🇲🇰",
      "🇳🇴",
      "🇴🇲",
      "🇵🇰",
      "🇵🇼",
      "🇵🇸",
      "🇵🇦",
      "🇵🇬",
      "🇵🇾",
      "🇵🇪",
      "🇵🇭",
      "🇵🇳",
      "🇵🇱",
      "🇵🇹",
      "🇵🇷",
      "🇶🇦",
      "🇷🇪",
      "🇷🇴",
      "🇷🇺",
      "🇷🇼",
      "🇼🇸",
      "🇸🇲",
      "🇸🇹",
      "🇸🇦",
      "🇸🇳",
      "🇷🇸",
      "🇸🇨",
      "🇸🇱",
      "🇸🇬",
      "🇸🇽",
      "🇸🇰",
      "🇸🇮",
      "🇸🇧",
      "🇸🇴",
      "🇿🇦",
      "🇬🇸",
      "🇰🇷",
      "🇸🇸",
      "🇪🇸",
      "🇱🇰",
      "🇧🇱",
      "🇸🇭",
      "🇰🇳",
      "🇱🇨",
      "🇵🇲",
      "🇻🇨",
      "🇸🇩",
      "🇸🇷",
      "🇸🇪",
      "🇨🇭",
      "🇸🇾",
      "🇹🇼",
      "🇹🇯",
      "🇹🇿",
      "🇹🇭",
      "🇹🇱",
      "🇹🇬",
      "🇹🇰",
      "🇹🇴",
      "🇹🇹",
      "🇹🇳",
      "🇹🇷",
      "🇹🇲",
      "🇹🇨",
      "🇹🇻",
      "🇺🇬",
      "🇺🇦",
      "🇦🇪",
      "🇬🇧",
      "🇺🇸",
      "🇺🇾",
      "🇺🇿",
      "🇻🇺",
      "🇻🇦",
      "🇻🇪",
      "🇻🇳",
      "🇼🇫",
      "🇪🇭",
      "🇾🇪",
      "🇿🇲",
      "🇿🇼",
      "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    ],
  },
];

const getFileType = (file: File): AttachmentFile["type"] => {
  if (file.type.startsWith("image/")) return "image";
  if (file.type.startsWith("video/")) return "video";
  if (file.type.startsWith("audio/")) return "audio";
  if (file.type === "application/pdf") return "pdf";
  return "document";
};

interface MessageInputProps {
  placeholder?: string;
  isSending?: boolean;
  replyTarget: ReplyTarget | null;
  onCancelReply: () => void;
  onSend: (
    content: string,
    attachments: AttachmentFile[],
    replyToId: string | null,
  ) => Promise<void>;
  currentUserImage: string | null;
  currentUserName: string;
}

const MessageInput: React.FC<MessageInputProps> = ({
  placeholder = "Type a message...",
  isSending = false,
  replyTarget,
  onCancelReply,
  onSend,
  currentUserImage,
  currentUserName,
}) => {
  const [text, setText] = useState("");
  const [attachments, setAttachments] = useState<AttachmentFile[]>([]);
  const [showEmoji, setShowEmoji] = useState(false);
  const [activeCategory, setActiveCategory] = useState(0);
  const [isDragging, setIsDragging] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const emojiPickerRef = useRef<HTMLDivElement>(null);
  const emojiBtnRef = useRef<HTMLButtonElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const tabsRef = useRef<HTMLDivElement>(null);

  // Close emoji picker on outside click (not on the toggle button itself)
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (
        emojiPickerRef.current &&
        !emojiPickerRef.current.contains(e.target as Node) &&
        emojiBtnRef.current &&
        !emojiBtnRef.current.contains(e.target as Node)
      ) {
        setShowEmoji(false);
      }
    };
    if (showEmoji) document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [showEmoji]);

  const handleSend = async () => {
    if ((!text.trim() && attachments.length === 0) || isSending) return;
    await onSend(text.trim(), attachments, replyTarget?.id ?? null);
    setText("");
    setAttachments([]);
    setShowEmoji(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  // Append emoji WITHOUT closing picker
  const appendEmoji = (emoji: string) => {
    setText((prev) => prev + emoji);
    inputRef.current?.focus();
  };

  const handleFiles = (files: FileList | null) => {
    if (!files) return;
    const next: AttachmentFile[] = Array.from(files).map((file) => {
      const type = getFileType(file);
      const previewUrl = type === "image" ? URL.createObjectURL(file) : null;
      return { file, previewUrl, type };
    });
    setAttachments((prev) => [...prev, ...next]);
  };

  const removeAttachment = (index: number) => {
    setAttachments((prev) => {
      const updated = [...prev];
      const url = updated[index].previewUrl;
      if (url) URL.revokeObjectURL(url);
      updated.splice(index, 1);
      return updated;
    });
  };

  const initials =
    currentUserName
      .split(" ")
      .filter(Boolean)
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2) || "Me";

  return (
    <div
      className={`border-t border-gray-100 transition-colors ${isDragging ? "bg-blue-50" : "bg-white"}`}
      onDragOver={(e) => {
        e.preventDefault();
        setIsDragging(true);
      }}
      onDragLeave={() => setIsDragging(false)}
      onDrop={(e) => {
        e.preventDefault();
        setIsDragging(false);
        handleFiles(e.dataTransfer.files);
      }}
    >
      {/* Reply preview */}
      {replyTarget && (
        <div className="pt-2 px-4">
          <ReplyPreview
            senderName={replyTarget.senderName}
            content={replyTarget.content}
            onCancel={onCancelReply}
          />
        </div>
      )}

      {/* Attachment previews */}
      {attachments.length > 0 && (
        <div className="flex gap-2 px-4 pt-3 flex-wrap">
          {attachments.map((att, i) => (
            <div key={i} className="relative group">
              {att.previewUrl ? (
                <img
                  src={att.previewUrl}
                  alt="attachment"
                  className="w-14 h-14 object-cover rounded-lg border border-gray-200"
                />
              ) : (
                <div className="w-14 h-14 bg-gray-100 rounded-lg border border-gray-200 flex flex-col items-center justify-center gap-1">
                  {att.type === "pdf" ? (
                    <FileText size={16} className="text-red-500" />
                  ) : (
                    <ImageIcon size={16} className="text-gray-400" />
                  )}
                  <span className="text-[10px] text-gray-500 truncate w-12 text-center px-1">
                    {att.file.name}
                  </span>
                </div>
              )}
              <button
                type="button"
                onClick={() => removeAttachment(i)}
                className="absolute -top-1.5 -right-1.5 w-4 h-4 bg-red-500 text-white rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <X size={10} />
              </button>
            </div>
          ))}
        </div>
      )}

      {isDragging && (
        <p className="text-center py-3 text-sm text-blue-500 font-medium">
          Drop files to attach
        </p>
      )}

      {/* Input row */}
      <div className="flex items-center gap-2 px-4 py-3">
        {/* Avatar */}
        <div className="flex-shrink-0">
          {currentUserImage ? (
            <img
              src={currentUserImage}
              alt={currentUserName}
              className="w-8 h-8 rounded-full object-cover"
            />
          ) : (
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#0C2340] to-[#1a3a5c] flex items-center justify-center text-white text-xs font-semibold">
              {initials}
            </div>
          )}
        </div>

        {/* Text input + action icons */}
        <div className="flex-1 flex items-center gap-2 bg-gray-50 rounded-xl px-3 py-2 border border-gray-200 focus-within:border-blue-400 focus-within:bg-white transition-colors min-w-0">
          <input
            ref={inputRef}
            type="text"
            placeholder={placeholder}
            value={text}
            onChange={(e) => setText(e.target.value)}
            onKeyDown={handleKeyDown}
            className="flex-1 outline-none bg-transparent text-sm text-gray-800 placeholder-gray-400 min-w-0"
          />
          <button
            type="button"
            onClick={() => fileInputRef.current?.click()}
            className="text-gray-400 hover:text-blue-500 transition-colors p-0.5 flex-shrink-0"
            title="Attach file"
          >
            <Paperclip size={15} />
          </button>
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={(e) => handleFiles(e.target.files)}
            accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.xls,.xlsx,.txt"
          />
          <button
            ref={emojiBtnRef}
            type="button"
            onClick={() => setShowEmoji((p) => !p)}
            className={`p-0.5 flex-shrink-0 transition-colors ${showEmoji ? "text-yellow-500" : "text-gray-400 hover:text-yellow-500"}`}
            title="Emoji"
          >
            <Smile size={15} />
          </button>
        </div>

        {/* Send */}
        <button
          type="button"
          onClick={handleSend}
          disabled={(!text.trim() && attachments.length === 0) || isSending}
          className="p-2.5 bg-[#0C2340] text-white rounded-xl hover:bg-[#1a3a5c] disabled:opacity-40 disabled:cursor-not-allowed transition-colors flex-shrink-0"
          title="Send (Enter)"
        >
          <Send size={15} />
        </button>
      </div>

      {/* ── Compact Emoji Picker ──────────────────────────────────────────────
          Fixed 300px wide, 260px tall grid area, scrollable per category.
          Tabs scroll horizontally. Picker stays open until outside click.   */}
      {showEmoji && (
        <div
          ref={emojiPickerRef}
          className="absolute bottom-16 right-4 z-40 bg-white rounded-2xl shadow-2xl border border-gray-200 overflow-hidden flex flex-col"
          style={{ width: 308, maxHeight: 320 }}
        >
          {/* Category tab strip — horizontally scrollable */}
          <div
            ref={tabsRef}
            className="flex overflow-x-auto border-b border-gray-100 bg-gray-50 flex-shrink-0"
            style={{ scrollbarWidth: "none" }}
          >
            {EMOJI_CATEGORIES.map((cat, i) => (
              <button
                key={cat.label}
                type="button"
                title={cat.label}
                onClick={() => setActiveCategory(i)}
                className={`flex-shrink-0 px-2 py-2 text-base transition-colors border-b-2 ${
                  activeCategory === i
                    ? "border-blue-500 bg-white"
                    : "border-transparent hover:bg-gray-100"
                }`}
              >
                {cat.icon}
              </button>
            ))}
          </div>

          {/* Category label */}
          <div className="px-3 py-1 text-[10px] font-semibold text-gray-400 uppercase tracking-widest flex-shrink-0 bg-white border-b border-gray-50">
            {EMOJI_CATEGORIES[activeCategory].label} ·{" "}
            {EMOJI_CATEGORIES[activeCategory].emojis.length}
          </div>

          {/* Emoji grid — scrollable */}
          <div className="overflow-y-auto flex-1 p-2" style={{ minHeight: 0 }}>
            <div className="grid grid-cols-9 gap-0.5">
              {EMOJI_CATEGORIES[activeCategory].emojis.map((emoji, idx) => (
                <button
                  key={`${emoji}-${idx}`}
                  type="button"
                  onClick={() => appendEmoji(emoji)}
                  className="flex items-center justify-center w-7 h-7 text-base rounded-lg hover:bg-gray-100 active:bg-gray-200 transition-colors leading-none"
                  title={emoji}
                >
                  {emoji}
                </button>
              ))}
            </div>
          </div>

          {/* Footer — preview + close */}
          <div className="flex-shrink-0 border-t border-gray-100 px-3 py-1.5 flex items-center justify-between bg-white">
            <span className="text-xs text-gray-400 truncate max-w-[180px]">
              {text ? `…${text.slice(-12)}` : "Select emoji to insert"}
            </span>
            <button
              type="button"
              onClick={() => setShowEmoji(false)}
              className="text-xs text-gray-400 hover:text-gray-600 flex-shrink-0 ml-2"
            >
              Close ✕
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default MessageInput;
